// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realtimeReconnectBackoff = (tries: number) =>
  [1000, 2000, 5000, 10000][tries - 1] ?? 10000;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
      heartbeatIntervalMs: 15000,
      reconnectAfterMs: realtimeReconnectBackoff,
      logger: (kind, msg, data) => {
        const prefix = "[Supabase Realtime]";
        if (kind === "error") {
          console.error(prefix, msg, data ?? {});
        } else if (kind === "warn") {
          console.warn(prefix, msg, data ?? {});
        } else if (kind === "info") {
          console.info(prefix, msg, data ?? {});
        }
      },
    },
  }
);
